name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: Output GitHub context
        # run: echo "${{ variable_name }}" # print variable
        # run: echo "${{ toJSON(github) }}" # print github context parsed to json
        run: echo "${{ toJSON(github.event) }}"