name: Test Project
# on: workflow_dispatch # trigger event - manual , other described: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
#       - name: Print greeting
#         run: echo "No elo"      # komenda bashowa
#       - name: Multiline         # komenda bashowa multiline
#         run: |
#             echo "First output"
#             echo "Second output"
      - name: Get code
        uses: actions/checkout@v3 #         action defined in github
        #with: # arguments passed to action (depends from action)
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying"